"""Add Provincia and Municipio models

Revision ID: 0f6548bca26e
Revises: a98e3f5c908a
Create Date: 2026-06-11 10:30:31.828697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0f6548bca26e'
down_revision: Union[str, None] = 'a98e3f5c908a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provincias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_index(op.f('ix_provincias_id'), 'provincias', ['id'], unique=False)
    op.create_table('municipios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provincia_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['provincia_id'], ['provincias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_municipios_id'), 'municipios', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_municipios_id'), table_name='municipios')
    op.drop_table('municipios')
    op.drop_index(op.f('ix_provincias_id'), table_name='provincias')
    op.drop_table('provincias')
    # ### end Alembic commands ###