"""Add Notificacao and PedidoPromocao models

Revision ID: 323fce88fcab
Revises: ea0523db86ad
Create Date: 2026-06-15 02:14:45.751738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '323fce88fcab'
down_revision: Union[str, None] = 'ea0523db86ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notificacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('utilizador_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=150), nullable=False),
    sa.Column('mensagem', sa.Text(), nullable=False),
    sa.Column('lida', sa.Boolean(), nullable=True),
    sa.Column('tipo', sa.Enum('sistema', 'pedido', 'promocao', 'mensagem', name='tiponotificacaoenum'), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['utilizador_id'], ['utilizadores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notificacoes_id'), 'notificacoes', ['id'], unique=False)
    op.create_table('pedidos_promocao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendedor_id', sa.Integer(), nullable=False),
    sa.Column('mensagem_solicitacao', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('pendente', 'aprovado', 'rejeitado', name='statuspedidopromocaoenum'), nullable=True),
    sa.Column('observacoes_admin', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['vendedor_id'], ['perfis_vendedor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pedidos_promocao_id'), 'pedidos_promocao', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pedidos_promocao_id'), table_name='pedidos_promocao')
    op.drop_table('pedidos_promocao')
    op.drop_index(op.f('ix_notificacoes_id'), table_name='notificacoes')
    op.drop_table('notificacoes')
    # ### end Alembic commands ###