"""Add latitude and longitude to Endereco

Revision ID: 3a474861868f
Revises: 76ebeb48ba59
Create Date: 2026-07-07 22:16:17.185983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '3a474861868f'
down_revision: Union[str, None] = '76ebeb48ba59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enderecos', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('enderecos', sa.Column('longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('enderecos', 'longitude')
    op.drop_column('enderecos', 'latitude')
    # ### end Alembic commands ###