"""Add MensagemChat

Revision ID: 76ebeb48ba59
Revises: 323fce88fcab
Create Date: 2026-07-07 21:38:41.655824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '76ebeb48ba59'
down_revision: Union[str, None] = '323fce88fcab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mensagens_chat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('remetente_id', sa.Integer(), nullable=False),
    sa.Column('destinatario_id', sa.Integer(), nullable=False),
    sa.Column('conteudo', sa.Text(), nullable=False),
    sa.Column('lida', sa.Boolean(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['destinatario_id'], ['utilizadores.id'], ),
    sa.ForeignKeyConstraint(['remetente_id'], ['utilizadores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mensagens_chat_id'), 'mensagens_chat', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mensagens_chat_id'), table_name='mensagens_chat')
    op.drop_table('mensagens_chat')
    # ### end Alembic commands ###