"""initial_migration

Revision ID: a98e3f5c908a
Revises: 
Create Date: 2026-05-25 21:37:38.237078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a98e3f5c908a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('icone_url', sa.String(length=500), nullable=True),
    sa.Column('categoria_pai_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(length=20), nullable=True),
    sa.Column('status', sa.Enum('ativo', 'inativo', name='categoriastatusenum'), nullable=True),
    sa.Column('ordem', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['categoria_pai_id'], ['categorias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categorias_id'), 'categorias', ['id'], unique=False)
    op.create_table('utilizadores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_completo', sa.String(length=200), nullable=False),
    sa.Column('nome_utilizador', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('numero_telefone', sa.String(length=20), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('data_nascimento', sa.Date(), nullable=True),
    sa.Column('genero', sa.Enum('masculino', 'feminino', 'outro', name='generoenum'), nullable=True),
    sa.Column('foto_perfil_url', sa.String(length=500), nullable=True),
    sa.Column('tipo_utilizador', sa.Enum('comprador', 'vendedor', 'admin', name='tipoutilizadorenum'), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('email_verificado', sa.Boolean(), nullable=True),
    sa.Column('telefone_verificado', sa.Boolean(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.Column('ultimo_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_telefone')
    )
    op.create_index(op.f('ix_utilizadores_email'), 'utilizadores', ['email'], unique=True)
    op.create_index(op.f('ix_utilizadores_id'), 'utilizadores', ['id'], unique=False)
    op.create_index(op.f('ix_utilizadores_nome_utilizador'), 'utilizadores', ['nome_utilizador'], unique=True)
    op.create_table('codigos_verificacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('utilizador_id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=10), nullable=False),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('expira_em', sa.DateTime(), nullable=False),
    sa.Column('usado', sa.Boolean(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['utilizador_id'], ['utilizadores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_codigos_verificacao_id'), 'codigos_verificacao', ['id'], unique=False)
    op.create_table('documentos_bi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('utilizador_id', sa.Integer(), nullable=False),
    sa.Column('numero_bi', sa.String(length=30), nullable=False),
    sa.Column('data_emissao', sa.Date(), nullable=False),
    sa.Column('data_validade', sa.Date(), nullable=False),
    sa.Column('foto_bi_frente_url', sa.String(length=500), nullable=True),
    sa.Column('selfie_verificacao_url', sa.String(length=500), nullable=True),
    sa.Column('status_verificacao', sa.Enum('pendente', 'em_analise', 'aprovado', 'rejeitado', name='statusverificacaoenum'), nullable=True),
    sa.Column('observacao_rejeicao', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['utilizador_id'], ['utilizadores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_bi'),
    sa.UniqueConstraint('utilizador_id')
    )
    op.create_index(op.f('ix_documentos_bi_id'), 'documentos_bi', ['id'], unique=False)
    op.create_table('enderecos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('utilizador_id', sa.Integer(), nullable=False),
    sa.Column('provincia', sa.String(length=100), nullable=False),
    sa.Column('municipio', sa.String(length=100), nullable=False),
    sa.Column('bairro', sa.String(length=150), nullable=True),
    sa.Column('endereco_completo', sa.Text(), nullable=True),
    sa.Column('nif', sa.String(length=20), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['utilizador_id'], ['utilizadores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nif'),
    sa.UniqueConstraint('utilizador_id')
    )
    op.create_index(op.f('ix_enderecos_id'), 'enderecos', ['id'], unique=False)
    op.create_table('pedidos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comprador_id', sa.Integer(), nullable=False),
    sa.Column('numero_pedido', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('pendente', 'confirmado', 'em_processamento', 'enviado', 'entregue', 'cancelado', 'reembolsado', name='statuspedidoenum'), nullable=True),
    sa.Column('status_pagamento', sa.Enum('pendente', 'pago', 'falhou', 'reembolsado', name='statuspagamentoenum'), nullable=True),
    sa.Column('valor_subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('valor_entrega', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('valor_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('moeda', sa.String(length=5), nullable=True),
    sa.Column('endereco_entrega_provincia', sa.String(length=100), nullable=True),
    sa.Column('endereco_entrega_municipio', sa.String(length=100), nullable=True),
    sa.Column('endereco_entrega_bairro', sa.String(length=150), nullable=True),
    sa.Column('endereco_entrega_completo', sa.Text(), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['comprador_id'], ['utilizadores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_pedido')
    )
    op.create_index(op.f('ix_pedidos_id'), 'pedidos', ['id'], unique=False)
    op.create_table('perfis_vendedor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('utilizador_id', sa.Integer(), nullable=False),
    sa.Column('nome_loja', sa.String(length=150), nullable=False),
    sa.Column('descricao_loja', sa.Text(), nullable=True),
    sa.Column('logo_loja_url', sa.String(length=500), nullable=True),
    sa.Column('banner_loja_url', sa.String(length=500), nullable=True),
    sa.Column('tipo_vendedor', sa.Enum('individual', 'empresa', name='tipovendedorenum'), nullable=True),
    sa.Column('tipo_loja', sa.Enum('produtos', 'servicos', 'ambos', name='tipolojaenum'), nullable=True),
    sa.Column('verificado', sa.Boolean(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('avaliacao_media', sa.Float(), nullable=True),
    sa.Column('total_vendas', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['utilizador_id'], ['utilizadores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('utilizador_id')
    )
    op.create_index(op.f('ix_perfis_vendedor_id'), 'perfis_vendedor', ['id'], unique=False)
    op.create_index(op.f('ix_perfis_vendedor_nome_loja'), 'perfis_vendedor', ['nome_loja'], unique=True)
    op.create_table('pagamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.Column('metodo', sa.String(length=50), nullable=False),
    sa.Column('referencia_externa', sa.String(length=200), nullable=True),
    sa.Column('valor', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('moeda', sa.String(length=5), nullable=True),
    sa.Column('status', sa.Enum('pendente', 'pago', 'falhou', 'reembolsado', name='statuspagamentoenum'), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('pago_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pedido_id')
    )
    op.create_index(op.f('ix_pagamentos_id'), 'pagamentos', ['id'], unique=False)
    op.create_table('produtos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendedor_id', sa.Integer(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=True),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('preco', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('preco_promocional', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.Column('sku', sa.String(length=100), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('destaque', sa.Boolean(), nullable=True),
    sa.Column('avaliacao_media', sa.Float(), nullable=True),
    sa.Column('total_avaliacoes', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ),
    sa.ForeignKeyConstraint(['vendedor_id'], ['perfis_vendedor.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku')
    )
    op.create_index(op.f('ix_produtos_id'), 'produtos', ['id'], unique=False)
    op.create_index(op.f('ix_produtos_nome'), 'produtos', ['nome'], unique=False)
    op.create_table('servicos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendedor_id', sa.Integer(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=True),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('preco_base', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('duracao_estimada', sa.String(length=100), nullable=True),
    sa.Column('disponivel_online', sa.Boolean(), nullable=True),
    sa.Column('disponivel_presencial', sa.Boolean(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('destaque', sa.Boolean(), nullable=True),
    sa.Column('avaliacao_media', sa.Float(), nullable=True),
    sa.Column('total_avaliacoes', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ),
    sa.ForeignKeyConstraint(['vendedor_id'], ['perfis_vendedor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_servicos_id'), 'servicos', ['id'], unique=False)
    op.create_index(op.f('ix_servicos_nome'), 'servicos', ['nome'], unique=False)
    op.create_table('avaliacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('avaliador_id', sa.Integer(), nullable=False),
    sa.Column('vendedor_id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=True),
    sa.Column('servico_id', sa.Integer(), nullable=True),
    sa.Column('nota', sa.Integer(), nullable=False),
    sa.Column('comentario', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['avaliador_id'], ['utilizadores.id'], ),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ),
    sa.ForeignKeyConstraint(['servico_id'], ['servicos.id'], ),
    sa.ForeignKeyConstraint(['vendedor_id'], ['perfis_vendedor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_avaliacoes_id'), 'avaliacoes', ['id'], unique=False)
    op.create_table('imagens_produto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('principal', sa.Boolean(), nullable=True),
    sa.Column('ordem', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_imagens_produto_id'), 'imagens_produto', ['id'], unique=False)
    op.create_table('imagens_servico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('servico_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('principal', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['servico_id'], ['servicos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_imagens_servico_id'), 'imagens_servico', ['id'], unique=False)
    op.create_table('itens_pedido',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('vendedor_id', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('preco_unitario', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos.id'], ),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ),
    sa.ForeignKeyConstraint(['vendedor_id'], ['perfis_vendedor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_itens_pedido_id'), 'itens_pedido', ['id'], unique=False)
    op.create_table('pedidos_servico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comprador_id', sa.Integer(), nullable=False),
    sa.Column('servico_id', sa.Integer(), nullable=False),
    sa.Column('numero_pedido', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('pendente', 'confirmado', 'em_processamento', 'enviado', 'entregue', 'cancelado', 'reembolsado', name='statuspedidoenum'), nullable=True),
    sa.Column('status_pagamento', sa.Enum('pendente', 'pago', 'falhou', 'reembolsado', name='statuspagamentoenum'), nullable=True),
    sa.Column('data_agendada', sa.DateTime(), nullable=True),
    sa.Column('descricao_necessidade', sa.Text(), nullable=True),
    sa.Column('valor_acordado', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('moeda', sa.String(length=5), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['comprador_id'], ['utilizadores.id'], ),
    sa.ForeignKeyConstraint(['servico_id'], ['servicos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_pedido')
    )
    op.create_index(op.f('ix_pedidos_servico_id'), 'pedidos_servico', ['id'], unique=False)
    op.create_table('pagamentos_servico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pedido_servico_id', sa.Integer(), nullable=False),
    sa.Column('metodo', sa.String(length=50), nullable=False),
    sa.Column('referencia_externa', sa.String(length=200), nullable=True),
    sa.Column('valor', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('moeda', sa.String(length=5), nullable=True),
    sa.Column('status', sa.Enum('pendente', 'pago', 'falhou', 'reembolsado', name='statuspagamentoenum'), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('pago_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['pedido_servico_id'], ['pedidos_servico.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pedido_servico_id')
    )
    op.create_index(op.f('ix_pagamentos_servico_id'), 'pagamentos_servico', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pagamentos_servico_id'), table_name='pagamentos_servico')
    op.drop_table('pagamentos_servico')
    op.drop_index(op.f('ix_pedidos_servico_id'), table_name='pedidos_servico')
    op.drop_table('pedidos_servico')
    op.drop_index(op.f('ix_itens_pedido_id'), table_name='itens_pedido')
    op.drop_table('itens_pedido')
    op.drop_index(op.f('ix_imagens_servico_id'), table_name='imagens_servico')
    op.drop_table('imagens_servico')
    op.drop_index(op.f('ix_imagens_produto_id'), table_name='imagens_produto')
    op.drop_table('imagens_produto')
    op.drop_index(op.f('ix_avaliacoes_id'), table_name='avaliacoes')
    op.drop_table('avaliacoes')
    op.drop_index(op.f('ix_servicos_nome'), table_name='servicos')
    op.drop_index(op.f('ix_servicos_id'), table_name='servicos')
    op.drop_table('servicos')
    op.drop_index(op.f('ix_produtos_nome'), table_name='produtos')
    op.drop_index(op.f('ix_produtos_id'), table_name='produtos')
    op.drop_table('produtos')
    op.drop_index(op.f('ix_pagamentos_id'), table_name='pagamentos')
    op.drop_table('pagamentos')
    op.drop_index(op.f('ix_perfis_vendedor_nome_loja'), table_name='perfis_vendedor')
    op.drop_index(op.f('ix_perfis_vendedor_id'), table_name='perfis_vendedor')
    op.drop_table('perfis_vendedor')
    op.drop_index(op.f('ix_pedidos_id'), table_name='pedidos')
    op.drop_table('pedidos')
    op.drop_index(op.f('ix_enderecos_id'), table_name='enderecos')
    op.drop_table('enderecos')
    op.drop_index(op.f('ix_documentos_bi_id'), table_name='documentos_bi')
    op.drop_table('documentos_bi')
    op.drop_index(op.f('ix_codigos_verificacao_id'), table_name='codigos_verificacao')
    op.drop_table('codigos_verificacao')
    op.drop_index(op.f('ix_utilizadores_nome_utilizador'), table_name='utilizadores')
    op.drop_index(op.f('ix_utilizadores_id'), table_name='utilizadores')
    op.drop_index(op.f('ix_utilizadores_email'), table_name='utilizadores')
    op.drop_table('utilizadores')
    op.drop_index(op.f('ix_categorias_id'), table_name='categorias')
    op.drop_table('categorias')
    # ### end Alembic commands ###