"""Add iban and comprovativo_url

Revision ID: ea0523db86ad
Revises: 0f6548bca26e
Create Date: 2026-06-12 08:44:22.011881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ea0523db86ad'
down_revision: Union[str, None] = '0f6548bca26e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pagamentos', sa.Column('comprovativo_url', sa.String(length=500), nullable=True))
    op.add_column('pagamentos_servico', sa.Column('comprovativo_url', sa.String(length=500), nullable=True))
    op.add_column('perfis_vendedor', sa.Column('iban', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('perfis_vendedor', 'iban')
    op.drop_column('pagamentos_servico', 'comprovativo_url')
    op.drop_column('pagamentos', 'comprovativo_url')
    # ### end Alembic commands ###